[package]
name = "SimpleCounter"
version = "1.0.0"
authors = ["Your Name <your.email@example.com>"]

[addresses]
counter_addr = "_"

[dev-addresses]
counter_addr = "0x006e8e66e34913ae5c9e2603a833f3680f0975b53a4ed48977ad6f102df1860e"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]